{
  "openapi": "3.0.3",
"info":{
    "title": "API - Hotel Management",
    "description": "CRUD, DDL e MDL entre banco MSSQL com auxílio do sequalize para consumo em diferentes plataformas",
    "termsOfService": "Null",
    "contact":{
        "email": "OctocatsUnip@gmail.com"
    },
    "version": "1.0.0",
"servers": [
    {
        "url": "http://localhost:5000",
        "description": "API dev"
    }
]},
"paths":{
    "/pessoas":{
        "post":{
           "summary" : "Cadastro de Pessoa",
           "description": "Rota para cadastro de pessoa",
           "tags": ["Pessoas"],
           "requestBody":{
               "content": {
                   "application/json":{
                       "schema": {
                            "$ref": "#/components/schemas/Pessoas"
                       },
                       "examples": {
                            "pessoa" : {
                                "value":{
                                    "nome": "John Doe",
                                    "rg": "256889984545",
                                    "cpf": "1436589612425",
                                    "data_nascimento": 25101981,
                                    "sexo": "Masculino"
                                }
                            }
                       }
                   }
               }
           },
           "responses": {
               "200":{
                   "description": "OK",
                   "content": {
                       "application/json":{
                           "schema":{
                            "type": "object",
                            "$ref": "#/components/schemas/Pessoas"
                           }
                       }
                   }
               }
           }
        },
        "get": {
            "summary": "Lista de pessoas",
            "description": "Listagem de todas as Pessoas",
            "tags": ["Pessoas"],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Pessoas"
                             }
                            }
                        }
                    }
                }
    }
      } 
    },
    "/pessoas/{cpf}":{
        "get":{
            "summary": "Achar pessoa por CPF",
            "description": "Traz os registros de uma pessoa pelo CPF",
            "tags": ["Pessoas"],
            "parameters": [{
                "in": "path",
                "name": "cpf",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Pessoas"
                             }
                            }
                        }
                    }
                }
        }
    }
},
    "/pessoas/endereco/{pessoa_id}":{
        "get":{
            "summary": "Trazer endereços pessoa",
            "description": "Traz todos os endereços vinculados a pessoa",
            "tags": ["Pessoas"],
            "parameters": [{
                "in": "path",
                "name": "pessoa_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Pessoa_Enderecos"
                             }
                            }
                        }
                    }
                }
        }
        },
        "post":{
            "summary" : "Cadastro de Endereços pessoa",
            "description": "Rota para cadastro de endereços em uma pessoa",
            "tags": ["Pessoas"],
            "parameters": [{
                "in": "path",
                "name": "pessoa_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "requestBody":{
                "content": {
                    "application/json":{
                        "schema": {
                             "$ref": "#/components/schemas/Enderecos"
                        },
                        "examples": {
                             "pessoa" : {
                                 "value":{
                                     "logradouro": "Avenida do Café",
                                     "numero": 270,
                                     "bairro": "Vila Tibério",
                                     "cidade": "Ribeirão Preto",
                                     "estado": "São Paulo",
                                     "cep": 1569887
                                 }
                             }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "object",
                             "$ref": "#/components/schemas/Pessoa_Enderecos"
                            }
                        }
                    }
                }
            }
         }
    },
    "/pessoas/telefones/{pessoa_id}": {
        "get":{
            "summary": "Trazer telefones pessoa",
            "description": "Traz todos os telefones vinculados a pessoa",
            "tags": ["Pessoas"],
            "parameters": [{
                "in": "path",
                "name": "pessoa_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Pessoa_Telefones"
                             }
                            }
                        }
                    }
                }
        }
        },
        "post":{
            "summary" : "Cadastro de Telefones pessoa",
            "description": "Rota para cadastro de telefones em uma pessoa",
            "tags": ["Pessoas"],
            "parameters": [{
                "in": "path",
                "name": "pessoa_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "requestBody":{
                "content": {
                    "application/json":{
                        "schema": {
                             "$ref": "#/components/schemas/Telefones"
                        },
                        "examples": {
                             "pessoa" : {
                                 "value":{
                                    "numero": 169852632,
                                     "tipo": "celular auxiliar"
                                 }
                             }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "object",
                             "$ref": "#/components/schemas/Pessoa_Telefones"
                            }
                        }
                    }
                }
            }
         }
    },
    "/status":{
        "get":{
            "summary": "Trazer todos os status",
            "description": "Traz todos os status cadastrados",
            "tags": ["Status"],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Status"
                             }
                            }
                        }
                    }
                }
        }
        },
        "post":{
            "summary" : "Cadastro de Endereços pessoa",
            "description": "Rota para cadastro de endereços em uma pessoa",
            "tags": ["Status"],            
            "requestBody":{
                "content": {
                    "application/json":{
                        "schema": {
                             "$ref": "#/components/schemas/Status"
                        },
                        "examples": {
                             "pessoa" : {
                                 "value":{
                                     "logradouro": "disponivel"
                                 }
                             }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "object",
                             "$ref": "#/components/schemas/Status"
                            }
                        }
                    }
                }
            }
         }
    },
    "/status/{nome_status}":{
        "get":{
            "summary": "Trazer status específico por nome",
            "description": "Traz status específico pelo nome",
            "tags": ["Status"],
            "parameters": [{
                "in": "path",
                "name": "nome_status",
                "required": true,
                "schema":{
                    "type":"string",
                    "minimum": 1
                }
            }],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Status"
                             }
                            }
                        }
                    }
                }
        }
        }
    },
    "/quartos": {
        "get":{
            "summary": "Trazer todos os quartos",
            "description": "Traz todos os quartos cadastrados",
            "tags": ["Quartos"],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Quartos"
                             }
                            }
                        }
                    }
                }
        }
    },
    "post":{
        "summary" : "Cadastro de Quartos",
        "description": "Rota para cadastro de Quartos",
        "tags": ["Quartos"],            
        "requestBody":{
            "content": {
                "application/json":{
                    "schema": {
                         "$ref": "#/components/schemas/Quartos"
                    },
                    "examples": {
                         "pessoa" : {
                             "value":{
                                 "nome_quarto": "Delux",
                                 "valor_quarto": 120,
                                 "quantia_camas": 1,
                                 "quantia_banheiros": 1,
                                 "img_quarto": "1",
                                 "descricao_quarto": "Um quarto cofortável"
                             }
                         }
                    }
                }
            }
        },
        "responses": {
            "200":{
                "description": "OK",
                "content": {
                    "application/json":{
                        "schema":{
                         "type": "object",
                         "$ref": "#/components/schemas/Quartos"
                        }
                    }
                }
            }
        }
     }
    },
    "/quartos/{nome_quarto}":{
        "post":{
            "summary" : "Atualizar status de um quarto",
            "description": "Rota para Atualizar status de um quarto",
            "tags": ["Quartos"],
            "parameters": [{
                "in": "path",
                "name": "nome_quarto",
                "required": true,
                "schema":{
                    "type":"string",
                    "minimum": 1
                }
            }],
            "requestBody":{
                "content": {
                    "application/json":{
                        "schema": {
                             "$ref": "#/components/schemas/Status"
                        },
                        "examples": {
                             "pessoa" : {
                                 "value":{
                                    "nome_status": "ocupado"
                                 }
                             }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "object",
                             "$ref": "#/components/schemas/Quartos"
                            }
                        }
                    }
                }
            }
         }
    },
    "/funcionario/{pessoa_id}":{
        "get":{
            "summary": "Trazer funcionário por pessoa",
            "description": "Traz dados funcionário por pessoa",
            "tags": ["Funcionario"],
            "parameters": [{
                "in": "path",
                "name": "pessoa_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Pessoa_Funcionario"
                             }
                            }
                        }
                    }
                }
        }
        },
        "post":{
            "summary" : "Cadastro de Funcionario por pessoa",
            "description": "Rota para cadastro de Funcionario por pessoa",
            "tags": ["Funcionario"],
            "parameters": [{
                "in": "path",
                "name": "pessoa_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "requestBody":{
                "content": {
                    "application/json":{
                        "schema": {
                             "$ref": "#/components/schemas/funcionario"
                        },
                        "examples": {
                             "pessoa" : {
                                 "value":{
                                     "salario": 2500
                                 }
                             }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "object",
                             "$ref": "#/components/schemas/Pessoa_Funcionario"
                            }
                        }
                    }
                }
            }
         }
    },
    "/user_sistema/{funcionario_id}": {
        "get":{
            "summary": "Trazer usuário por funcionário",
            "description": "Traz dados do usuário por funcionário",
            "tags": ["Funcionario"],
            "parameters": [{
                "in": "path",
                "name": "funcionario_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Funcionario_User"
                             }
                            }
                        }
                    }
                }
        }
        },
        "post":{
            "summary" : "Cadastro de Usuário por funcionário",
            "description": "Rota para cadastro de  Usuário por funcionário",
            "tags": ["Funcionario"],
            "parameters": [{
                "in": "path",
                "name": "funcionario_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "requestBody":{
                "content": {
                    "application/json":{
                        "schema": {
                             "$ref": "#/components/schemas/user_sistema"
                        },
                        "examples": {
                             "pessoa" : {
                                 "value":{
                                     "nome_usuario": "ana paula santos",
                                     "senha": "teste123"                                     
                                 }
                             }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "object",
                             "$ref": "#/components/schemas/Funcionario_User"
                            }
                        }
                    }
                }
            }
         }
    },
    "/user_cliente/{pessoa_id}": {
        "get":{
            "summary": "Trazer usuário por pessoa",
            "description": "Traz dados do usuário por pessoa",
            "tags": ["Pessoas"],
            "parameters": [{
                "in": "path",
                "name": "pessoa_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Pessoa_User"
                             }
                            }
                        }
                    }
                }
        }
        },
        "post":{
            "summary" : "Cadastro de Usuário por pessoa",
            "description": "Rota para cadastro de  Usuário por pessoa",
            "tags": ["Pessoas"],
            "parameters": [{
                "in": "path",
                "name": "pessoa_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "requestBody":{
                "content": {
                    "application/json":{
                        "schema": {
                             "$ref": "#/components/schemas/user_cliente"
                        },
                        "examples": {
                             "pessoa" : {
                                 "value":{
                                     "email": "ana_paula23@gmail.com",
                                     "senha": "teste123"                                     
                                 }
                             }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "object",
                             "$ref": "#/components/schemas/Pessoa_User"
                            }
                        }
                    }
                }
            }
         }
    },
    "/beneficio":{
        "get":{
            "summary": "Trazer beneficios",
            "description": "Traz beneficios",
            "tags": ["Beneficios"],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/Beneficios"
                             }
                            }
                        }
                    }
                }
        }
        },
        "post":{
            "summary" : "Cadastro de beneficios",
            "description": "Rota para cadastro de beneficios",
            "tags": ["Beneficios"],
            "requestBody":{
                "content": {
                    "application/json":{
                        "schema": {
                             "$ref": "#/components/schemas/Beneficios"
                        },
                        "examples": {
                             "pessoa" : {
                                 "value":{
                                     "nome_beneficio": "almoço",
                                     "valor_beneficio": 250                                     
                                 }
                             }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "object",
                             "$ref": "#/components/schemas/Beneficios"
                            }
                        }
                    }
                }
            }
         }
    },
    "/reservas/:quarto_id": {
        "get":{
            "summary": "Trazer reserva por quarto",
            "description": "Traz reserva por quarto",
            "tags": ["Reservas"],
            "parameters": [{
                "in": "path",
                "name": "quarto_id",
                "required": true,
                "schema":{
                    "type":"integer",
                    "minimum": 1
                }
            }],
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "array",
                             "items":{
                                "$ref": "#/components/schemas/ReservasPessoas"
                             }
                            }
                        }
                    }
                }
        }
        }        
    },
    "/reservas": {
        "post": {
            "summary" : "Cadastro de Reservas",
            "description": "Rota para cadastro de Reservas",
            "tags": ["Reservas"],            
            "requestBody":{
                "content": {
                    "application/json":{
                        "schema": {
                             "$ref": "#/components/schemas/Reservas"
                        },
                        "examples": {
                             "pessoa" : {
                                 "value":{
                                     "data_inicio": "20191225",
                                     "data_final": "20191225",
                                     "valores_beneficios": 3500,
                                     "quarto_id": 1,  
                                     "pessoas": [1, 2, 3]
                                 }
                             }
                        }
                    }
                }
            },
            "responses": {
                "200":{
                    "description": "OK",
                    "content": {
                        "application/json":{
                            "schema":{
                             "type": "object",
                             "$ref": "#/components/schemas/ReservasPessoas"
                            }
                        }
                    }
                }
            }
        }
    }
  },
  

  "components":{
    "schemas":{
        "Pessoas":{
            "type": "object",
            "properties": {
                "nome": {
                    "type": "string"
                },
                "rg": {
                    "type": "string"
                },
                "cpf": {
                  "type": "string"
              },
              "data_nascimento": {
                "type": "number"
            },
            "sexo": {
              "type": "string"
          }        
        }
      },
      "Pessoa_Enderecos":{
        "type": "object",
        "properties": {
            "nome": {
                "type": "string"
            },
            "rg": {
                "type": "string"
            },
            "cpf": {
              "type": "string"
          },
          "data_nascimento": {
            "type": "number"
        },
        "sexo": {
          "type": "string"
      },
      "logradouro":{
        "type": "string"
      },
      "numero":{
        "type": "number"
      },
      "bairro":{
        "type": "string"
      },
      "cidade":{
        "type": "string"
      },
      "estado":{
        "type": "string"
      },
      "cep":{
        "type": "number"
      }
    }
      },
      "Enderecos": {
        "type": "object",
        "properties": {
            "logradouro":{
                "type": "string"
              },
              "numero":{
                "type": "number"
              },
              "bairro":{
                "type": "string"
              },
              "cidade":{
                "type": "string"
              },
              "estado":{
                "type": "string"
              },
              "cep":{
                "type": "number"
              }
        }
      },
      "Pessoa_Telefones":{
        "type": "object",
        "properties": {
            "nome": {
                "type": "string"
            },
            "rg": {
                "type": "string"
            },
            "cpf": {
              "type": "string"
          },
          "data_nascimento": {
            "type": "number"
        },
        "sexo": {
          "type": "string"
      },
      "numero":{
        "type": "number"
      },
    "tipo":{
        "type": "string"
      }
    }
      },
      "Telefones":{
        "type": "object",
        "properties": {
            "numero":{
                "type": "number"
              },
            "tipo":{
                "type": "string"
              }
        }
      },
      "Status":{
        "type": "object",
        "properties": {
            "nome_status":{
                "type": "string"
              }
        }
      },
      "Quartos":{
        "type": "object",
        "properties": {
            "nome_quarto": {
                "type": "string"
            },
            "valor_quarto": {
                "type": "number"
            },
            "quantia_camas": {
              "type": "number"
          },
          "quantia_banheiros": {
            "type": "number"
        },
        "img_quarto": {
          "type": "string"
      },
      "descricao_quarto": {
        "type": "string"
    }    
      }
    },
    "Pessoa_Funcionario": {
        "type": "object",
        "properties": {
            "nome": {
                "type": "string"
            },
            "rg": {
                "type": "string"
            },
            "cpf": {
              "type": "string"
          },
          "data_nascimento": {
            "type": "number"
        },
        "sexo": {
          "type": "string"
      },
      "salario":{
        "type": "number"
      }
    }
  },
  "Funcionario":{
    "type": "object",
    "properties": {
        "salario":{
            "type": "number"
          }
    }
  },
  "user_sistema":{
    "type": "object",
    "properties": {
        "nome_usuario":{
            "type": "string"
          },
          "senha":{
            "type": "string"
          }
    }
  },
  "Funcionario_User": {
    "type": "object",
    "properties": {
        "salario":{
            "type": "number"
          },
        "nome_usuario":{
            "type": "string"
          },
          "senha":{
            "type": "string"
          }
    }
  },
  "user_cliente":{
    "type": "object",
    "properties": {
        "email":{
            "type": "string"
          },
          "senha":{
            "type": "string"
          }
    }
  },
  "Pessoa_User": {
    "type": "object",
    "properties": {
        "nome": {
            "type": "string"
        },
        "rg": {
            "type": "string"
        },
        "cpf": {
          "type": "string"
      },
      "data_nascimento": {
        "type": "number"
    },
    "sexo": {
      "type": "string"
  },
  "email":{
    "type": "string"
  },
  "senha":{
    "type": "string"
  }  
    }
  },
  "Beneficios":{
    "type": "object",
    "properties": {
        "nome_beneficio":{
            "type": "string"
          },
          "valor_beneficio":{
            "type": "number"
          }
    }
  },
  "ReservasPessoas":{
    "type": "object",
    "properties": {
        "data_inicio":{
            "type": "number"
          },
          "data_final":{
            "type": "number"
          },
          "data_checkout":{
            "type": "number"
          },
          "valor_diarias":{
            "type": "number"
          },
          "valores_beneficios":{
            "type": "number"
          },
          "nome": {
            "type": "string"
        },
        "rg": {
            "type": "string"
        },
        "cpf": {
          "type": "string"
      },
      "data_nascimento": {
        "type": "number"
    },
    "sexo": {
      "type": "string"
  }


    } 
  },
  "Reservas":{
    "type": "object",
    "properties": {
        "data_inicio":{
            "type": "number"
          },
          "data_final":{
            "type": "number"
          },
          "valores_beneficios":{
            "type": "number"
          },
          "quarto_id":{
            "type": "number"
          },
          "pessoas":{
            "type": "array"
          }
    }
  }

}  
}  
}           